https://d2l.ai/chapter_deep-learning-computation/parameters.html

In [1]:
%matplotlib inline
import torch as tc
import tensorflow as tf
import mxnet as mx
from mxnet import np as mxnp
from mxnet import npx as npx
npx.set_np()
# import numpy as np

from d2l import mxnet as mxd2l  # Use MXNet as the backend
from d2l import torch as tcd2l  # Use PyTorch as the backend
from d2l import tensorflow as tfd2l  # Use TensorFlow as the backend

from d2l import mxnet as mxd2l  # Use MXNet as the backend
from d2l import torch as tcd2l  # Use PyTorch as the backend
from d2l import tensorflow as tfd2l  # Use TensorFlow as the backend

tc.__version__,tf.__version__,mx.__version__

('1.6.0', '2.3.1', '1.7.0')

In [2]:
from mxnet.gluon import nn
from mxnet import init

In [3]:
net=nn.Sequential()
# with net.name_scope():
#     net.add(nn.Dense(8,activation='relu'))
#     net.add(nn.Dense(1))

net.add(nn.Dense(8,activation='relu'))
net.add(nn.Dense(1))
net.initialize()

In [4]:
net

Sequential(
  (0): Dense(-1 -> 8, Activation(relu))
  (1): Dense(-1 -> 1, linear)
)

In [5]:
# net.name_scope??

In [6]:
X=mxnp.random.uniform(size=(2,4))
X.shape,X

((2, 4),
 array([[0.5488135 , 0.5928446 , 0.71518934, 0.84426576],
        [0.60276335, 0.8579456 , 0.5448832 , 0.8472517 ]]))

In [7]:
net(X)

array([[0.0054572 ],
       [0.00488594]])

In [19]:
net[0].params

dense0_ (
  Parameter dense0_weight (shape=(8, 4), dtype=float32)
  Parameter dense0_bias (shape=(8,), dtype=float32)
)

In [20]:
net[1].params

dense1_ (
  Parameter dense1_weight (shape=(1, 8), dtype=float32)
  Parameter dense1_bias (shape=(1,), dtype=float32)
)

In [21]:
net[1].weight,net[1].bias

(Parameter dense1_weight (shape=(1, 8), dtype=float32),
 Parameter dense1_bias (shape=(1,), dtype=float32))

In [22]:
net[1].weight.data()

array([[ 0.06700657, -0.00369488,  0.0418822 ,  0.0421275 , -0.00539289,
         0.00286685,  0.03927409,  0.02504314]])

In [23]:
net[1].bias.data()

array([0.])

In [13]:
net[1].weight.grad()

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
net[1].bias.grad()

array([0.])

In [26]:
ps0=net[0].collect_params()
ps0

dense0_ (
  Parameter dense0_weight (shape=(8, 4), dtype=float32)
  Parameter dense0_bias (shape=(8,), dtype=float32)
)

In [27]:
ps0['dense0_weight']

Parameter dense0_weight (shape=(8, 4), dtype=float32)

In [28]:
ps0['dense0_weight'].data()

array([[-0.01068833,  0.01729892,  0.02042518, -0.01618656],
       [-0.00873779, -0.02834515,  0.05484822, -0.06206018],
       [ 0.06491279, -0.03182812, -0.01631819, -0.00312688],
       [ 0.0408415 ,  0.04370362,  0.00404529, -0.0028032 ],
       [ 0.00952624, -0.01501013,  0.05958354,  0.04705103],
       [-0.06005495, -0.02276454, -0.0578019 ,  0.02074406],
       [-0.06716943, -0.01844618,  0.04656678,  0.06400172],
       [ 0.03894195, -0.05035089,  0.0518017 ,  0.05181222]])

In [29]:
ps0['dense0_weight'].grad()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
net.collect_params()

sequential0_ (
  Parameter dense0_weight (shape=(8, 4), dtype=float32)
  Parameter dense0_bias (shape=(8,), dtype=float32)
  Parameter dense1_weight (shape=(1, 8), dtype=float32)
  Parameter dense1_bias (shape=(1,), dtype=float32)
)

In [18]:
net.collect_params()['dense0_weight']

Parameter dense0_weight (shape=(8, 4), dtype=float32)

In [ ]:
net.collect_params()['dense4_weight'].data()

In [ ]:
net.collect_params()['dense5_bias'].data()

In [31]:
def block1():
    net=nn.Sequential()
    net.add(nn.Dense(32,activation='relu'))
    net.add(nn.Dense(16,activation='relu'))
    return net

In [32]:
def block2():
    net=nn.Sequential()
    for _ in range(4):
        net.add(block1())
    return net

In [33]:
rgnet=nn.Sequential()
rgnet.add(block2())
rgnet.add(nn.Dense(10))
rgnet.initialize()


In [34]:
rgnet(X)

array([[-6.3465850e-09, -1.1096741e-09,  6.4161783e-09,  6.6354131e-09,
        -1.1265494e-09,  1.3285140e-10,  9.3619370e-09,  3.2229102e-09,
         5.9429874e-09,  8.8181427e-09],
       [-8.6219414e-09, -7.5150730e-10,  8.3133251e-09,  8.9321119e-09,
        -1.6740000e-09,  3.2406028e-10,  1.2115975e-08,  4.4926440e-09,
         8.0741742e-09,  1.2075873e-08]])

In [35]:
X.shape,rgnet(X).shape

((2, 4), (2, 10))

In [36]:
rgnet.summary(X)

--------------------------------------------------------------------------------
        Layer (type)                                Output Shape         Param #
               Input                                      (2, 4)               0
        Activation-1                                     (2, 32)               0
             Dense-2                                     (2, 32)             160
        Activation-3                                     (2, 16)               0
             Dense-4                                     (2, 16)             528
        Activation-5                                     (2, 32)               0
             Dense-6                                     (2, 32)             544
        Activation-7                                     (2, 16)               0
             Dense-8                                     (2, 16)             528
        Activation-9                                     (2, 32)               0
            Dense-10        

In [38]:
rgnet.collect_params

<bound method Block.collect_params of Sequential(
  (0): Sequential(
    (0): Sequential(
      (0): Dense(4 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (1): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (2): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
    (3): Sequential(
      (0): Dense(16 -> 32, Activation(relu))
      (1): Dense(32 -> 16, Activation(relu))
    )
  )
  (1): Dense(16 -> 10, linear)
)>

In [48]:
rgnet[0][1][1],rgnet[0][1][1].weight.data().shape

(Dense(32 -> 16, Activation(relu)), (16, 32))

In [50]:
all_ps=rgnet.collect_params()
all_ps

sequential1_ (
  Parameter dense2_weight (shape=(32, 4), dtype=float32)
  Parameter dense2_bias (shape=(32,), dtype=float32)
  Parameter dense3_weight (shape=(16, 32), dtype=float32)
  Parameter dense3_bias (shape=(16,), dtype=float32)
  Parameter dense4_weight (shape=(32, 16), dtype=float32)
  Parameter dense4_bias (shape=(32,), dtype=float32)
  Parameter dense5_weight (shape=(16, 32), dtype=float32)
  Parameter dense5_bias (shape=(16,), dtype=float32)
  Parameter dense6_weight (shape=(32, 16), dtype=float32)
  Parameter dense6_bias (shape=(32,), dtype=float32)
  Parameter dense7_weight (shape=(16, 32), dtype=float32)
  Parameter dense7_bias (shape=(16,), dtype=float32)
  Parameter dense8_weight (shape=(32, 16), dtype=float32)
  Parameter dense8_bias (shape=(32,), dtype=float32)
  Parameter dense9_weight (shape=(16, 32), dtype=float32)
  Parameter dense9_bias (shape=(16,), dtype=float32)
  Parameter dense10_weight (shape=(10, 16), dtype=float32)
  Parameter dense10_bias (shape=(10,), 

In [57]:
all_ps.prefix

'sequential1_'

In [58]:
all_ps.items()

odict_items([('dense2_weight', Parameter dense2_weight (shape=(32, 4), dtype=float32)), ('dense2_bias', Parameter dense2_bias (shape=(32,), dtype=float32)), ('dense3_weight', Parameter dense3_weight (shape=(16, 32), dtype=float32)), ('dense3_bias', Parameter dense3_bias (shape=(16,), dtype=float32)), ('dense4_weight', Parameter dense4_weight (shape=(32, 16), dtype=float32)), ('dense4_bias', Parameter dense4_bias (shape=(32,), dtype=float32)), ('dense5_weight', Parameter dense5_weight (shape=(16, 32), dtype=float32)), ('dense5_bias', Parameter dense5_bias (shape=(16,), dtype=float32)), ('dense6_weight', Parameter dense6_weight (shape=(32, 16), dtype=float32)), ('dense6_bias', Parameter dense6_bias (shape=(32,), dtype=float32)), ('dense7_weight', Parameter dense7_weight (shape=(16, 32), dtype=float32)), ('dense7_bias', Parameter dense7_bias (shape=(16,), dtype=float32)), ('dense8_weight', Parameter dense8_weight (shape=(32, 16), dtype=float32)), ('dense8_bias', Parameter dense8_bias (sha

In [59]:
all_ps.values()

odict_values([Parameter dense2_weight (shape=(32, 4), dtype=float32), Parameter dense2_bias (shape=(32,), dtype=float32), Parameter dense3_weight (shape=(16, 32), dtype=float32), Parameter dense3_bias (shape=(16,), dtype=float32), Parameter dense4_weight (shape=(32, 16), dtype=float32), Parameter dense4_bias (shape=(32,), dtype=float32), Parameter dense5_weight (shape=(16, 32), dtype=float32), Parameter dense5_bias (shape=(16,), dtype=float32), Parameter dense6_weight (shape=(32, 16), dtype=float32), Parameter dense6_bias (shape=(32,), dtype=float32), Parameter dense7_weight (shape=(16, 32), dtype=float32), Parameter dense7_bias (shape=(16,), dtype=float32), Parameter dense8_weight (shape=(32, 16), dtype=float32), Parameter dense8_bias (shape=(32,), dtype=float32), Parameter dense9_weight (shape=(16, 32), dtype=float32), Parameter dense9_bias (shape=(16,), dtype=float32), Parameter dense10_weight (shape=(10, 16), dtype=float32), Parameter dense10_bias (shape=(10,), dtype=float32)])

In [62]:
all_ps.__dir__()

['_prefix',
 '_params',
 '_shared',
 '__module__',
 '__doc__',
 '__init__',
 '__repr__',
 '__getitem__',
 '__iter__',
 'items',
 'keys',
 'values',
 'prefix',
 '_get_impl',
 'get',
 'get_constant',
 'update',
 'initialize',
 'zero_grad',
 'reset_ctx',
 'list_ctx',
 'setattr',
 'save',
 'load',
 'load_dict',
 '__dict__',
 '__weakref__',
 '__hash__',
 '__str__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__new__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [63]:
# all_ps??

In [61]:
# rgnet[0][0][0].weight.data()
rgnet[0][0][0].weight.data

<bound method Parameter.data of Parameter dense6_weight (shape=(32, 4), dtype=float32)>

In [56]:
rgnet[0][0][0].weight.data().shape

(32, 4)

In [62]:
rgnet[1]

Dense(16 -> 10, linear)

In [63]:
rgnet[0][1]

Sequential(
  (0): Dense(16 -> 32, Activation(relu))
  (1): Dense(32 -> 16, Activation(relu))
)

In [64]:
rgnet[0][2]

Sequential(
  (0): Dense(16 -> 32, Activation(relu))
  (1): Dense(32 -> 16, Activation(relu))
)

In [65]:
rgnet[0][3]

Sequential(
  (0): Dense(16 -> 32, Activation(relu))
  (1): Dense(32 -> 16, Activation(relu))
)

In [67]:
rgnet[1]

Dense(16 -> 10, linear)

In [71]:
ps=rgnet.collect_params

In [79]:
len(rgnet)

2

In [82]:
type(rgnet)

mxnet.gluon.nn.basic_layers.Sequential

In [83]:
list(rgnet)

[Sequential(
   (0): Sequential(
     (0): Dense(4 -> 32, Activation(relu))
     (1): Dense(32 -> 16, Activation(relu))
   )
   (1): Sequential(
     (0): Dense(16 -> 32, Activation(relu))
     (1): Dense(32 -> 16, Activation(relu))
   )
   (2): Sequential(
     (0): Dense(16 -> 32, Activation(relu))
     (1): Dense(32 -> 16, Activation(relu))
   )
   (3): Sequential(
     (0): Dense(16 -> 32, Activation(relu))
     (1): Dense(32 -> 16, Activation(relu))
   )
 ),
 Dense(16 -> 10, linear)]

In [80]:
len(rgnet[0])

4

In [81]:
len(rgnet[1])

TypeError: object of type 'Dense' has no len()

In [193]:
def print_net_layers_details(net,l=-1):
    if not isinstance(net,nn.Sequential):
        #print(net)
        pass
    else:
        #print(f"Type:{type(net)}")
        l+=1
        for i in range(len(net)):
            print(f"  {'  '*l}({l}):Type:{type(net[i])}")
            print_net_layers_details(net[i],l)            

In [203]:
def print_net_layers_details(net,l=-1):
    if not isinstance(net,nn.Sequential):
        #print(net)
        pass
    else:
        l+=1
        for i in range(len(net)):
            l_name=net[i].name
            l_weight_name=l_name+'_weight'
            #print(f"  {'  '*l}({l}):{l_name},shape:{net[i].collect_params()[l_weight_name].data().shape}")
            print(f"  {'   '*l}({l}):{l_name}")
            print_net_layers_details(net[i],l)   

In [204]:
# len(net),net.qe

In [205]:
print_net_layers_details(net)

  (0):dense4
  (0):dense5


In [206]:
print_net_layers_details(rgnet)

  (0):sequential5
     (1):sequential6
        (2):dense6
        (2):dense7
     (1):sequential7
        (2):dense8
        (2):dense9
     (1):sequential8
        (2):dense10
        (2):dense11
     (1):sequential9
        (2):dense12
        (2):dense13
  (0):dense14


In [172]:
rgnet.dense6_weight

AttributeError: 'Sequential' object has no attribute 'dense6_weight'

In [174]:
rgnet.collect_params()

sequential4_ (
  Parameter dense6_weight (shape=(32, 4), dtype=float32)
  Parameter dense6_bias (shape=(32,), dtype=float32)
  Parameter dense7_weight (shape=(16, 32), dtype=float32)
  Parameter dense7_bias (shape=(16,), dtype=float32)
  Parameter dense8_weight (shape=(32, 16), dtype=float32)
  Parameter dense8_bias (shape=(32,), dtype=float32)
  Parameter dense9_weight (shape=(16, 32), dtype=float32)
  Parameter dense9_bias (shape=(16,), dtype=float32)
  Parameter dense10_weight (shape=(32, 16), dtype=float32)
  Parameter dense10_bias (shape=(32,), dtype=float32)
  Parameter dense11_weight (shape=(16, 32), dtype=float32)
  Parameter dense11_bias (shape=(16,), dtype=float32)
  Parameter dense12_weight (shape=(32, 16), dtype=float32)
  Parameter dense12_bias (shape=(32,), dtype=float32)
  Parameter dense13_weight (shape=(16, 32), dtype=float32)
  Parameter dense13_bias (shape=(16,), dtype=float32)
  Parameter dense14_weight (shape=(10, 16), dtype=float32)
  Parameter dense14_bias (shape

In [177]:
rgnet.collect_params()["dense6_weight"]

Parameter dense6_weight (shape=(32, 4), dtype=float32)

In [162]:
net.name

'sequential3'

In [68]:
rgnet[0][0][0].weight.data()[0]

array([-0.05344158,  0.03088857,  0.01958894,  0.01148278])

In [75]:
rgnet.initialize(init=init.Normal(),force_reinit=True,verbose=False)

In [76]:
rgnet[0][0][0].weight.data()[0]

array([ 0.00055116, -0.01317326,  0.01149097, -0.00646666])

In [77]:
rgnet[0][0][0].bias.data()[0]

array(0.)

In [78]:
rgnet[0][0][0].bias.data()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
rgnet[0][0][0].bias.initialize(init=init.Constant(42), force_reinit=True)

In [83]:
rgnet[0][0][0].bias.data()

array([42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42.,
       42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42., 42.,
       42., 42., 42., 42., 42., 42.])

In [84]:
rgnet[0][0][0].bias.initialize(init=init.Normal(), force_reinit=True)

In [85]:
rgnet[0][0][0].bias.data()

array([ 0.0110995 ,  0.01027754,  0.00117048,  0.0123198 , -0.01141737,
        0.00026106,  0.00560496,  0.00522628, -0.01829545,  0.01075405,
        0.00580612, -0.000322  , -0.00479999, -0.00329021,  0.00689593,
       -0.02144433,  0.01524227, -0.00942547, -0.00180339,  0.01470467,
       -0.00947481, -0.00560179, -0.02078937, -0.01483103, -0.01200161,
        0.00546303,  0.01246248,  0.00443168,  0.00041833,  0.00467015,
       -0.00327042,  0.01185161])

In [160]:
init.Initializer.__dict__

mappingproxy({'__module__': 'mxnet.initializer',
              '__doc__': 'The base class of an initializer.',
              '__init__': <function mxnet.initializer.Initializer.__init__(self, **kwargs)>,
              'set_verbosity': <function mxnet.initializer.Initializer.set_verbosity(self, verbose=False, print_func=None)>,
              '_verbose_print': <function mxnet.initializer.Initializer._verbose_print(self, desc, init, arr)>,
              'dumps': <function mxnet.initializer.Initializer.dumps(self)>,
              '__call__': <function mxnet.initializer.Initializer.__call__(self, desc, arr)>,
              '_legacy_init': <function mxnet.initializer.Initializer._legacy_init(self, name, arr)>,
              '_init_bilinear': <function mxnet.initializer.Initializer._init_bilinear(self, _, arr)>,
              '_init_loc_bias': <function mxnet.initializer.Initializer._init_loc_bias(self, _, arr)>,
              '_init_zero': <function mxnet.initializer.Initializer._init_zero(s

In [149]:
class MyInit(init.Initializer):
    def _init_weight(self,name,data):
        print("Init",name,data.shape)
        data[:]=mxnp.random.uniform(-10,10,data.shape)
        print(f"-10,10:\n{data}")
        factor=mxnp.abs(data)>=5
        print(f"factor:{factor}")
        data *=factor
        print(f"factored data:\n{data}")
        self._init_bias(name, data)
    def _init_bias(self, name, data):
        print(f"_init_bias called!,name={name},data={data}")        
        data[:]=1.11

In [150]:
net

Sequential(
  (0): Dense(4 -> 8, Activation(relu))
  (1): Dense(8 -> 1, linear)
)

In [152]:
# net.

In [153]:
net.initialize(init=MyInit(),force_reinit=True)

Init dense0_weight (8, 4)
-10,10:
[[ 6.6337414  7.07259    9.012396  -9.367755 ]
 [-2.7147179  6.1081753  7.739073  -7.7084026]
 [ 7.177149  -5.229972   1.4760866  1.8462448]
 [-7.0485115  6.2846203  4.0829706  7.8691273]
 [ 8.895758   7.628229   6.386101  -8.593758 ]
 [-8.469378  -8.417879  -9.549531  -0.8415394]
 [-0.787282   3.1703672  8.260176   8.013813 ]
 [ 4.447256  -8.846274   9.987713  -2.7920098]]
factor:[[ True  True  True  True]
 [False  True  True  True]
 [ True  True False False]
 [ True  True False  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False False  True  True]
 [False  True  True False]]
factored data:
[[ 6.6337414  7.07259    9.012396  -9.367755 ]
 [-0.         6.1081753  7.739073  -7.7084026]
 [ 7.177149  -5.229972   0.         0.       ]
 [-7.0485115  6.2846203  0.         7.8691273]
 [ 8.895758   7.628229   6.386101  -8.593758 ]
 [-8.469378  -8.417879  -9.549531  -0.       ]
 [-0.         0.         8.260176   8.013813 ]
 [ 0.        -8.84627

In [161]:
net[0].bias.data()

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [170]:
net[0].bias.initialize(init=init.Constant(0.0),force_reinit=True)

In [171]:
# rgnet.initialize(init=MyInit(),force_reinit=True)

In [172]:
net[0].bias.data()

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [179]:
net[0].bias.data()[:]+=1.1

In [180]:
net[0].bias.data()

array([4.1, 4.1, 4.1, 4.1, 4.1, 4.1, 4.1, 4.1])

In [191]:
net[0].bias.set_data(1)

AttributeError: 'int' object has no attribute 'shape'

In [ ]:
net[0].bias.set_data

In [ ]:
net[0].bias.set_data

In [189]:
net.set_data??

Object `net.set_data` not found.


In [205]:
help(mx.gluon.Parameter)

Help on class Parameter in module mxnet.gluon.parameter:

class Parameter(builtins.object)
 |  Parameter(name, grad_req='write', shape=None, dtype=<class 'numpy.float32'>, lr_mult=1.0, wd_mult=1.0, init=None, allow_deferred_init=False, differentiable=True, stype='default', grad_stype='default')
 |  
 |  A Container holding parameters (weights) of Blocks.
 |  
 |  :py:class:`Parameter` holds a copy of the parameter on each :py:class:`Context` after
 |  it is initialized with ``Parameter.initialize(...)``. If :py:attr:`grad_req` is
 |  not ``'null'``, it will also hold a gradient array on each :py:class:`Context`::
 |  
 |      ctx = mx.gpu(0)
 |      x = mx.nd.zeros((16, 100), ctx=ctx)
 |      w = mx.gluon.Parameter('fc_weight', shape=(64, 100), init=mx.init.Xavier())
 |      b = mx.gluon.Parameter('fc_bias', shape=(64,), init=mx.init.Zero())
 |      w.initialize(ctx=ctx)
 |      b.initialize(ctx=ctx)
 |      out = mx.nd.FullyConnected(x, w.data(ctx), b.data(ctx), num_hidden=64)
 |  
 |

## ---5.2.3. Tied Parameters

In [227]:
net=nn.Sequential()
shared=nn.Dense(8,activation='relu')

In [228]:
net.add(nn.Dense(8,activation='relu'),
        shared,
        nn.Dense(8,activation='relu',params=shared.params),
        nn.Dense(10)
       )

In [229]:
net.initialize()
X = mxnp.random.uniform(size=(2, 20))
net(X)

array([[-2.1250595e-04,  1.8790623e-05, -8.4716550e-05, -5.5808996e-05,
        -5.9902501e-05,  5.3465628e-05, -3.5292582e-05,  3.8800637e-05,
        -1.4099345e-04,  3.2080083e-05],
       [-3.0736171e-04,  1.9917868e-05, -1.4329508e-04, -7.0946102e-05,
        -7.3313502e-05,  5.9338534e-05, -6.6079527e-05,  5.8100843e-05,
        -2.0833977e-04,  6.6165143e-05]])

In [230]:
net

Sequential(
  (0): Dense(20 -> 8, Activation(relu))
  (1): Dense(8 -> 8, Activation(relu))
  (2): Dense(8 -> 8, Activation(relu))
  (3): Dense(8 -> 10, linear)
)

In [231]:
net[1].weight.data()

array([[ 0.0003989 ,  0.06467754, -0.06415183, -0.0044894 ,  0.04645038,
        -0.03191967,  0.00962504,  0.00032905],
       [-0.05347276, -0.05808223,  0.06686059, -0.02243201, -0.02966708,
        -0.02598768, -0.03744306,  0.01313522],
       [ 0.05144552, -0.02406184,  0.03482223,  0.02472705, -0.00093874,
        -0.00144684,  0.05293112,  0.05540768],
       [-0.00513945, -0.05274353, -0.06629816, -0.06857597,  0.03105516,
        -0.00392253, -0.03308609, -0.03342582],
       [-0.02473748, -0.01061019,  0.06016981,  0.06766913,  0.01706763,
         0.06049497,  0.03693354, -0.01908711],
       [ 0.00470132,  0.02634631,  0.01266788, -0.02322487,  0.03734159,
        -0.01236327,  0.06247991, -0.06183095],
       [ 0.02938278, -0.05197422, -0.06606058,  0.03735435, -0.02002081,
         0.06628404,  0.03830533,  0.03782804],
       [-0.06532781,  0.05832445,  0.05319418, -0.02658434,  0.02415888,
        -0.01762218, -0.03679934, -0.06199735]])

In [232]:
net[2].weight.data()

array([[ 0.0003989 ,  0.06467754, -0.06415183, -0.0044894 ,  0.04645038,
        -0.03191967,  0.00962504,  0.00032905],
       [-0.05347276, -0.05808223,  0.06686059, -0.02243201, -0.02966708,
        -0.02598768, -0.03744306,  0.01313522],
       [ 0.05144552, -0.02406184,  0.03482223,  0.02472705, -0.00093874,
        -0.00144684,  0.05293112,  0.05540768],
       [-0.00513945, -0.05274353, -0.06629816, -0.06857597,  0.03105516,
        -0.00392253, -0.03308609, -0.03342582],
       [-0.02473748, -0.01061019,  0.06016981,  0.06766913,  0.01706763,
         0.06049497,  0.03693354, -0.01908711],
       [ 0.00470132,  0.02634631,  0.01266788, -0.02322487,  0.03734159,
        -0.01236327,  0.06247991, -0.06183095],
       [ 0.02938278, -0.05197422, -0.06606058,  0.03735435, -0.02002081,
         0.06628404,  0.03830533,  0.03782804],
       [-0.06532781,  0.05832445,  0.05319418, -0.02658434,  0.02415888,
        -0.01762218, -0.03679934, -0.06199735]])

In [233]:
net[1].weight.data()==net[2].weight.data()

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [234]:
net[1].weight.data()[0, 0] = 100

In [235]:
net[1].weight.data()

array([[ 1.0000000e+02,  6.4677544e-02, -6.4151831e-02, -4.4893995e-03,
         4.6450377e-02, -3.1919666e-02,  9.6250400e-03,  3.2905489e-04],
       [-5.3472757e-02, -5.8082234e-02,  6.6860594e-02, -2.2432011e-02,
        -2.9667076e-02, -2.5987685e-02, -3.7443057e-02,  1.3135217e-02],
       [ 5.1445521e-02, -2.4061840e-02,  3.4822233e-02,  2.4727054e-02,
        -9.3874335e-04, -1.4468357e-03,  5.2931115e-02,  5.5407681e-02],
       [-5.1394477e-03, -5.2743532e-02, -6.6298164e-02, -6.8575971e-02,
         3.1055160e-02, -3.9225295e-03, -3.3086088e-02, -3.3425819e-02],
       [-2.4737481e-02, -1.0610189e-02,  6.0169809e-02,  6.7669131e-02,
         1.7067634e-02,  6.0494967e-02,  3.6933541e-02, -1.9087110e-02],
       [ 4.7013164e-03,  2.6346311e-02,  1.2667879e-02, -2.3224872e-02,
         3.7341587e-02, -1.2363274e-02,  6.2479906e-02, -6.1830945e-02],
       [ 2.9382780e-02, -5.1974218e-02, -6.6060580e-02,  3.7354350e-02,
        -2.0020809e-02,  6.6284038e-02,  3.8305327e-02,  3

In [236]:
net[2].weight.data()

array([[ 1.0000000e+02,  6.4677544e-02, -6.4151831e-02, -4.4893995e-03,
         4.6450377e-02, -3.1919666e-02,  9.6250400e-03,  3.2905489e-04],
       [-5.3472757e-02, -5.8082234e-02,  6.6860594e-02, -2.2432011e-02,
        -2.9667076e-02, -2.5987685e-02, -3.7443057e-02,  1.3135217e-02],
       [ 5.1445521e-02, -2.4061840e-02,  3.4822233e-02,  2.4727054e-02,
        -9.3874335e-04, -1.4468357e-03,  5.2931115e-02,  5.5407681e-02],
       [-5.1394477e-03, -5.2743532e-02, -6.6298164e-02, -6.8575971e-02,
         3.1055160e-02, -3.9225295e-03, -3.3086088e-02, -3.3425819e-02],
       [-2.4737481e-02, -1.0610189e-02,  6.0169809e-02,  6.7669131e-02,
         1.7067634e-02,  6.0494967e-02,  3.6933541e-02, -1.9087110e-02],
       [ 4.7013164e-03,  2.6346311e-02,  1.2667879e-02, -2.3224872e-02,
         3.7341587e-02, -1.2363274e-02,  6.2479906e-02, -6.1830945e-02],
       [ 2.9382780e-02, -5.1974218e-02, -6.6060580e-02,  3.7354350e-02,
        -2.0020809e-02,  6.6284038e-02,  3.8305327e-02,  3

In [237]:
net[1].weight.data()==net[2].weight.data()

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [238]:
net[2].weight.data()[0,1]=10.

In [239]:
net[1].weight.data()[0,1]

array(10.)

In [240]:
net[1].weight.data()==net[2].weight.data()

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

##  --torch

In [358]:
import torch
from torch import nn

In [242]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[-0.0979],
        [-0.0531]], grad_fn=<AddmmBackward>)

In [244]:
net

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=1, bias=True)
)

In [245]:
net[0]

Linear(in_features=4, out_features=8, bias=True)

In [246]:
net[1]

ReLU()

In [247]:
net[2]

Linear(in_features=8, out_features=1, bias=True)

In [250]:
len(net)

3

In [251]:
net[3]

IndexError: index 3 is out of range

In [253]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[-0.2462, -0.0022,  0.2605, -0.2276,  0.1718,  0.1981,  0.0372,  0.0573]])),
             ('bias', tensor([0.0677]))])

In [254]:
net[2].weight

Parameter containing:
tensor([[-0.2462, -0.0022,  0.2605, -0.2276,  0.1718,  0.1981,  0.0372,  0.0573]],
       requires_grad=True)

In [255]:
net[2].weight.data

tensor([[-0.2462, -0.0022,  0.2605, -0.2276,  0.1718,  0.1981,  0.0372,  0.0573]])

In [256]:
net[2].weight.data.dtype

torch.float32

In [258]:
net[2].weight.grad,net[2].weight.grad

(None, None)

In [259]:
net.named_parameters()

<generator object Module.named_parameters at 0x0000020E41BE3040>

In [260]:
list(net.named_parameters())

[('0.weight',
  Parameter containing:
  tensor([[ 0.4088,  0.0157,  0.3174,  0.4552],
          [ 0.4190, -0.4450,  0.1210, -0.4408],
          [-0.4061,  0.1100,  0.1412,  0.1877],
          [ 0.2792,  0.4302, -0.2359, -0.0999],
          [-0.1740, -0.1502, -0.3748, -0.2132],
          [-0.2526,  0.4556, -0.2180, -0.3074],
          [ 0.2574, -0.2946,  0.1812, -0.3666],
          [ 0.0712,  0.2555,  0.3182,  0.3894]], requires_grad=True)),
 ('0.bias',
  Parameter containing:
  tensor([-0.2001, -0.1859,  0.0203,  0.4270,  0.0506,  0.4136,  0.2259,  0.1288],
         requires_grad=True)),
 ('2.weight',
  Parameter containing:
  tensor([[-0.2462, -0.0022,  0.2605, -0.2276,  0.1718,  0.1981,  0.0372,  0.0573]],
         requires_grad=True)),
 ('2.bias',
  Parameter containing:
  tensor([0.0677], requires_grad=True))]

In [261]:
[(name,param.shape) for name,param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

In [262]:
[(name,param.shape) for name,param in net[0].named_parameters()]

[('weight', torch.Size([8, 4])), ('bias', torch.Size([8]))]

In [263]:
[(name,param.shape) for name,param in net[2].named_parameters()]

[('weight', torch.Size([1, 8])), ('bias', torch.Size([1]))]

In [264]:
[(name,param.shape) for name,param in net[1].named_parameters()]

[]

In [265]:
net[2].state_dict()["weight"]

tensor([[-0.2462, -0.0022,  0.2605, -0.2276,  0.1718,  0.1981,  0.0372,  0.0573]])

In [266]:
net.state_dict()['0.weight']

tensor([[ 0.4088,  0.0157,  0.3174,  0.4552],
        [ 0.4190, -0.4450,  0.1210, -0.4408],
        [-0.4061,  0.1100,  0.1412,  0.1877],
        [ 0.2792,  0.4302, -0.2359, -0.0999],
        [-0.1740, -0.1502, -0.3748, -0.2132],
        [-0.2526,  0.4556, -0.2180, -0.3074],
        [ 0.2574, -0.2946,  0.1812, -0.3666],
        [ 0.0712,  0.2555,  0.3182,  0.3894]])

In [268]:
net[0].weight.data

tensor([[ 0.4088,  0.0157,  0.3174,  0.4552],
        [ 0.4190, -0.4450,  0.1210, -0.4408],
        [-0.4061,  0.1100,  0.1412,  0.1877],
        [ 0.2792,  0.4302, -0.2359, -0.0999],
        [-0.1740, -0.1502, -0.3748, -0.2132],
        [-0.2526,  0.4556, -0.2180, -0.3074],
        [ 0.2574, -0.2946,  0.1812, -0.3666],
        [ 0.0712,  0.2555,  0.3182,  0.3894]])

In [269]:
def block1():
    return nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                         nn.Linear(8, 4), nn.ReLU())

def block2():
    net = nn.Sequential()
    for i in range(4):
        # Nested here
        net.add_module(f'block {i}', block1())
    return net

rgnet = nn.Sequential(block2(), nn.Linear(4, 1))
rgnet(X)

tensor([[0.2787],
        [0.2788]], grad_fn=<AddmmBackward>)

In [270]:
rgnet

Sequential(
  (0): Sequential(
    (block 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block 3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)

In [276]:
rgnet[0][3][0].weight.data

tensor([[ 0.2465, -0.1762, -0.0527, -0.3288],
        [ 0.3619,  0.0370,  0.3797,  0.0367],
        [-0.1266,  0.2676, -0.4161, -0.4609],
        [-0.4198, -0.2046,  0.2989, -0.3051],
        [-0.1959,  0.2850, -0.0159,  0.4352],
        [-0.3871, -0.2042,  0.3062, -0.3165],
        [ 0.2053, -0.2228,  0.0427, -0.4909],
        [ 0.0053,  0.3339, -0.0767,  0.4009]])

In [277]:
rgnet[0][3][0].bias.data

tensor([-0.1548, -0.2233,  0.1993, -0.4676,  0.1049, -0.2364,  0.2601,  0.1327])

In [278]:
nn.Linear(4,8)

Linear(in_features=4, out_features=8, bias=True)

In [279]:
rgnet.modules()

<generator object Module.modules at 0x0000020E421A74A0>

In [348]:
# len(list(rgnet.modules())),list(rgnet.modules())

In [286]:
type(rgnet.modules())

generator

In [285]:
for m in rgnet.modules():
    print("___________")
    if isinstance(m,nn.Linear):
        print(m)

___________
___________
___________
___________
Linear(in_features=4, out_features=8, bias=True)
___________
___________
Linear(in_features=8, out_features=4, bias=True)
___________
___________
___________
Linear(in_features=4, out_features=8, bias=True)
___________
___________
Linear(in_features=8, out_features=4, bias=True)
___________
___________
___________
Linear(in_features=4, out_features=8, bias=True)
___________
___________
Linear(in_features=8, out_features=4, bias=True)
___________
___________
___________
Linear(in_features=4, out_features=8, bias=True)
___________
___________
Linear(in_features=8, out_features=4, bias=True)
___________
___________
Linear(in_features=4, out_features=1, bias=True)


In [351]:
def init_normal(m):
    if isinstance(m,nn.Linear):
        nn.init.normal_(m.weight,std=0.5)
        nn.init.ones_(m.bias)

In [352]:
rgnet.apply(init_normal);

In [353]:
rgnet[0][0][0].weight.data.std()

tensor(0.4334)

In [354]:
rgnet[0][0][0].bias.data

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [343]:
def init_module(m):
    for m in m.modules():
        if isinstance(m,nn.Linear):
            nn.init.normal_(m.weight,mean=3,std=10.)
            nn.init.constant_(m.bias,10)

In [344]:
init_module(rgnet)

In [345]:
rgnet[0][0][0].weight.data.std()

tensor(10.8022)

In [346]:
rgnet[0][0][0].weight.data.mean()

tensor(0.6286)

In [347]:
rgnet[0][0][0].bias.data

tensor([10., 10., 10., 10., 10., 10., 10., 10.])

In [359]:
shared_lin=nn.Linear(8,8)

In [361]:
type(shared_lin)

torch.nn.modules.linear.Linear

In [362]:
nn

<module 'torch.nn' from 'C:\\Users\\HP\\miniconda3\\envs\\d2l\\lib\\site-packages\\torch\\nn\\__init__.py'>

In [363]:
net=nn.Sequential(
    nn.Linear(4,8),nn.ReLU(),
    shared_lin,nn.ReLU(),
    nn.Linear(8,8),
    shared_lin
)

In [364]:
net

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=8, bias=True)
  (5): Linear(in_features=8, out_features=8, bias=True)
)

In [365]:
net[5].weight==net[2].weight

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])

In [366]:
id(net[5].weight)

2260263008064

In [367]:
id(net[2].weight)

2260263008064

##  --tensorflow

In [368]:
import tensorflow as tf
import numpy as np

In [369]:
net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4, activation=tf.nn.relu),
    tf.keras.layers.Dense(1),
])

In [370]:
net

In [375]:
X = tf.random.uniform((2, 4))
net(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.8270541 ],
       [0.94886285]], dtype=float32)>

In [376]:
net.layers

In [384]:
net.layers[1].weights[0].shape

TensorShape([4, 4])

In [403]:
for layer in net.layers:
    if isinstance(layer,tf.keras.layers.Dense):
        print(f"layer.weight.shape:{layer.weights[0].numpy().shape}")
        print(f"layer.bias.shape:{layer.weights[1].numpy().shape}")

layer.weight.shape:(4, 4)
layer.bias.shape:(4,)
layer.weight.shape:(4, 1)
layer.bias.shape:(1,)


In [391]:
net.layers[1].weights[0]*2+1

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.8333796 ,  1.4392475 ,  0.08520114,  1.0352645 ],
       [ 0.92579734,  0.4091096 ,  0.6356511 ,  2.6621976 ],
       [ 2.6561027 ,  1.8598822 , -0.6805105 , -0.7102002 ],
       [ 2.2602744 , -0.09433103,  2.3724084 ,  0.3400824 ]],
      dtype=float32)>

In [393]:
# tf.Variable??

In [395]:
net.get_weights()[0]

array([[-0.08331019,  0.21962374, -0.45739943,  0.01763225],
       [-0.03710133, -0.2954452 , -0.18217444,  0.83109885],
       [ 0.82805127,  0.42994112, -0.84025526, -0.8551001 ],
       [ 0.63013715, -0.5471655 ,  0.68620414, -0.3299588 ]],
      dtype=float32)

In [401]:
net.layers[1].weights[0].numpy().shape

(4, 4)

In [406]:
net.layers[1].weights[0]

<tf.Variable 'dense/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[-0.08331019,  0.21962374, -0.45739943,  0.01763225],
       [-0.03710133, -0.2954452 , -0.18217444,  0.83109885],
       [ 0.82805127,  0.42994112, -0.84025526, -0.8551001 ],
       [ 0.63013715, -0.5471655 ,  0.68620414, -0.3299588 ]],
      dtype=float32)>

In [408]:
net.layers[1].weights[0].numpy()

array([[-0.08331019,  0.21962374, -0.45739943,  0.01763225],
       [-0.03710133, -0.2954452 , -0.18217444,  0.83109885],
       [ 0.82805127,  0.42994112, -0.84025526, -0.8551001 ],
       [ 0.63013715, -0.5471655 ,  0.68620414, -0.3299588 ]],
      dtype=float32)

In [409]:
net.get_weights()

[array([[-0.08331019,  0.21962374, -0.45739943,  0.01763225],
        [-0.03710133, -0.2954452 , -0.18217444,  0.83109885],
        [ 0.82805127,  0.42994112, -0.84025526, -0.8551001 ],
        [ 0.63013715, -0.5471655 ,  0.68620414, -0.3299588 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[ 0.84085774],
        [-0.7947255 ],
        [-1.0606515 ],
        [-0.9609411 ]], dtype=float32),
 array([0.], dtype=float32)]

In [410]:
net.get_weights()[0]

array([[-0.08331019,  0.21962374, -0.45739943,  0.01763225],
       [-0.03710133, -0.2954452 , -0.18217444,  0.83109885],
       [ 0.82805127,  0.42994112, -0.84025526, -0.8551001 ],
       [ 0.63013715, -0.5471655 ,  0.68620414, -0.3299588 ]],
      dtype=float32)

In [412]:
# tf.keras.Sequential??

In [414]:
s=tf.keras.Sequential([
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4, activation=tf.nn.relu)],
        name="S_name")

In [415]:
s.name

'S_name'

In [416]:
s.name_scope()

'S_name/'

In [436]:
def block(name:str):
    s=tf.keras.Sequential([
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(4, activation=tf.nn.relu)],
        name=name)
    return s

In [437]:
s=block("BBB")

In [438]:
s.build(input_shape=(1,3))

In [439]:
s.name

'BBB'

In [440]:
s.get_weights()

[array([[-0.51507425,  0.7338506 , -0.36768752,  0.34003365],
        [-0.61569524, -0.39298964, -0.00611234,  0.6454723 ],
        [ 0.39660478,  0.41358864,  0.2742834 , -0.8049402 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [442]:
def block2():
    net = tf.keras.Sequential()
    for i in range(4):
        # Nested here
        net.add(block(name=f'block-{i}'))
    return net

In [443]:
rgnet = tf.keras.Sequential()
rgnet.add(block2())
rgnet.add(tf.keras.layers.Dense(1))
rgnet(X)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.1863406 ],
       [-0.11732443]], dtype=float32)>

In [444]:
X

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.62481904, 0.15839565, 0.7037914 , 0.7279985 ],
       [0.0504837 , 0.0635581 , 0.83265996, 0.70702875]], dtype=float32)>

In [445]:
rgnet.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_2 (Sequential)    (2, 4)                    80        
_________________________________________________________________
dense_11 (Dense)             (2, 1)                    5         
Total params: 85
Trainable params: 85
Non-trainable params: 0
_________________________________________________________________


In [447]:
tf.print(rgnet)

In [450]:
rgnet.layers

In [449]:
rgnet.layers[0]

In [451]:
rgnet.layers[0].layers

In [455]:
rgnet.layers[0].layers[1].name

'block-1'

In [456]:
rgnet.get_layer('block-1')

ValueError: No such layer: block-1.

In [457]:
rgnet.layers[0].get_layer('block-1')

In [459]:
rgnet.layers[0].get_layer('block-0').name

'block-0'

In [463]:
rgnet.layers[0].get_layer('block-0').weights[0].numpy()

array([[ 0.02415216,  0.53252774,  0.42252475,  0.7537069 ],
       [ 0.6008882 , -0.05484122,  0.29434568, -0.7257192 ],
       [ 0.43401533, -0.39216647, -0.76510835, -0.62729824],
       [ 0.07043988, -0.45436403,  0.29348308,  0.76853603]],
      dtype=float32)

In [465]:
rgnet.layers[0].layers[0].name

'block-0'

In [466]:
rgnet.layers[0].layers[0].weights[0].numpy()

array([[ 0.02415216,  0.53252774,  0.42252475,  0.7537069 ],
       [ 0.6008882 , -0.05484122,  0.29434568, -0.7257192 ],
       [ 0.43401533, -0.39216647, -0.76510835, -0.62729824],
       [ 0.07043988, -0.45436403,  0.29348308,  0.76853603]],
      dtype=float32)

In [468]:
rgnet.layers[0].name

'sequential_2'

In [470]:
rgnet.layers[0].layers[0].name

'block-0'

In [471]:
tf.keras.initializers.Initializer??

Init signature: tf.keras.initializers.Initializer()
Source:        
class Initializer(object):
  """Initializer base class: all Keras initializers inherit from this class.

  Initializers should implement a `__call__` method with the following
  signature:

  ```python
  def __call__(self, shape, dtype=None)`:
    # returns a tensor of shape `shape` and dtype `dtype`
    # containing values drawn from a distribution of your choice.
  ```

  Optionally, you an also implement the method `get_config` and the class
  method `from_config` in order to support serialization -- just like with
  any Keras object.

  Here's a simple example: a random normal initializer.

  ```python
  import tensorflow as tf

  class ExampleRandomNormal(tf.keras.initializers.Initializer):

    def __init__(self, mean, stddev):
      self.mean = mean
      self.stddev = stddev

    def __call__(self, shape, dtype=None)`:
      return tf.random.normal(
          shape, mean=self.mean, stddev=self.stddev, dtype=dty

In [509]:
class MyInit(tf.keras.initializers.Initializer):
    def __call__(self, shape, dtype=None):
        data=tf.random.uniform(shape,-10, 10, dtype=dtype)
        factor=(tf.abs(data)>=5)
        factor=tf.cast(factor,tf.float32)
        return data*factor

net = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(
        4,
        activation=tf.nn.relu,
        kernel_initializer=MyInit()),
    tf.keras.layers.Dense(1,kernel_initializer=MyInit()),
])

net(X)
print(net.layers[1].weights[0])

<tf.Variable 'dense_30/kernel:0' shape=(4, 4) dtype=float32, numpy=
array([[ 6.857296 ,  0.       ,  0.       , -0.       ],
       [ 9.202946 ,  8.291145 ,  0.       ,  7.466118 ],
       [-7.4632335, -0.       , -7.7842164,  0.       ],
       [ 5.173319 , -0.       , -5.302031 , -0.       ]], dtype=float32)>


In [510]:
net.layers[2].weights[0]

<tf.Variable 'dense_31/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[ 0.      ],
       [-8.78397 ],
       [-9.205301],
       [ 0.      ]], dtype=float32)>

In [503]:
data=tf.random.uniform((2,3), -10,10,dtype=tf.float32)

In [476]:
data

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 8.337114 ,  5.5709248, -5.218873 ],
       [ 6.2537155,  4.4574404, -6.261115 ]], dtype=float32)>

In [477]:
data>=5

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [ True, False, False]])>

In [512]:
factor=(tf.abs(data)>=5)
factor,type(factor)

(<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[False, False,  True],
        [ True,  True,  True]])>,
 tensorflow.python.framework.ops.EagerTensor)

In [492]:
factor=tf.cast(factor,tf.float32)
factor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 0., 1.]], dtype=float32)>

In [493]:
data*factor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 8.337114 ,  5.5709248, -5.218873 ],
       [ 6.2537155,  0.       , -6.261115 ]], dtype=float32)>

In [494]:
data

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 8.337114 ,  5.5709248, -5.218873 ],
       [ 6.2537155,  4.4574404, -6.261115 ]], dtype=float32)>

In [486]:
# factor*data

In [483]:
factor.float()

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'float'

In [484]:
tf.cast(factor,tf.float32)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 0.],
       [1., 0., 0.]], dtype=float32)>